### PR TITLE
Sort keys for more predictable display

### PR DESCRIPTION
**Pull request by okigan**

### CODE REVIEW

**Comment by mohsen1** [comment]
I don't think JSON Formatter should change order of the keys

**Comment by colmaengus** [comment]
I think this would be a nice feature, maybe as an option.
Otherwise every time the json loads you get the keys displayed in a different order.

**Comment by mohsen1** [comment]
As an option this will be very nice to have. Maybe an attribute:

```html
<json-formatter json="myJson" sort-keys="true"></json-formatter>
```

**Comment by mohsen1** [comment]
Please update this PR to allow sorting be an optional attribute directive.

**Comment by okigan** [comment]
As order of keys in JS is unpredictable and displaying them in sorted order is effectively free - I'll use that all the time.  

You can disposition this PR as you see fit.

**Comment by mohsen1** [comment]
I would merge it if it was exposed as an optional attribute but I don't have the time to do it myself. Please feel free to update the PR if you like this get merged.

**Pull request closed without merging**
