### PR TITLE
use constructor.name property by default for custom name, if defined

### PR DESCRIPTION
**Pull request by cozyazure**
For ES6, constructor's name will be the same as the class name of an object, and it will be stored under the `__proto__.constructor.name`. If this is defined, use this custom name instead.

### CODE REVIEW

**Comment by damianb** [comment]
Any way this could make its way into a new release?

**Comment by mohsen1** [comment]
I'll cut a release today

**Comment by damianb** [comment]
Thanks much!

**Comment by mohsen1** [comment]
Released in v0.7.0

**Pull request merged**
